spring:
  datasource:
    #  驱动
    driver-class-name: org.h2.Driver
    # h2 内存数据库 内存模式连接配置 库名: spring_security  mysql模式
    url: jdbc:h2:mem:spring_security;MODE=MySQL;DATABASE_TO_LOWER=TRUE
    # 初始化数据表 DDL
    schema: classpath:sql/ddl.sql
    #  初始化数据 DML
    data: classpath:sql/dml.sql
  h2:
    #    开启console 访问 默认false
    console:
      enabled: true
      settings:
        #      开启h2 console 跟踪 方便调试  默认 false
        trace: true
        #      允许console 远程访问 默认false
        web-allow-others: true
      #  h2 访问路径上下文
      path: /h2-console
  security:
    oauth2:
      client:
        registration:
          gitee:
            client-id: 2274094e86ac40f6a401883715ae539d14be2e1dfe4552cfbb71b768ae8ea452
            client-secret: b5245ca84327ce890372c69745c639c8c0dd9a5916ec3f7fb5fed5485e8d8433

# 日志
logging:
  level:
    cn.felord.spring.security.mapper: debug
    org.springframework.security: debug

# mybatis 配置
mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
  type-aliases-package: cn.felord.spring.security.entity
server:
  port: 8083
