spring:
  redis:
    host: 127.0.0.1
    database: 0
  thymeleaf:
    prefix: classpath:/views/
    suffix: .html
    cache: false
  mvc:
    throw-exception-if-no-handler-found: true
logging:
  level:
    org.springframework.web: info